# Site settings
author: Kristine Petrosyan
title: Going after my dreams!
header-img: img/home-bg.png
email: kristinelpetrosyan@gmail.com
copyright_name: Kristine Petrosyan
description: > # this means to ignore newlines until "baseurl:"
  How I decided to become a Data scientist
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kristinepetrosyan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
